create table
  public.stores (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    address text null,
    type text null,
    constraint stores_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.reviews (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    account_name text null,
    rating bigint null,
    description text null,
    store_id bigint null,
    constraint reviews_pkey primary key (id),
    constraint reviews_store_id_fkey foreign key (store_id) references stores (id)
  ) tablespace pg_default;

create table
  public.replies (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    review_id bigint null,
    account_name text null,
    description text null,
    constraint replies_pkey primary key (id),
    constraint replies_review_id_fkey foreign key (review_id) references reviews (id)
  ) tablespace pg_default;