create table
  public.stores (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    rating integer null,
    address text null,
    type text null,
    constraint stores_pkey primary key (id)
  ) tablespace pg_default;